# Exported from:        http://Anurags-MacBook-Pro.local:5516/
# Release version:      24.1.0

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: scm check
spec:
- template: check1
  scheduledStartDate: 2026-08-31T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: New task
      type: xlrelease.Task
    - name: New task
      type: xlrelease.Task
    - name: New task
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
